spring:
  application:
    name: user-service
  datasource:
#    url: jdbc:postgresql://postgresql:5432/postgres
    url: jdbc:postgresql://localhost:5433/postgres
    username: postgres
    password: password
  jpa:
    properties:
      hibernate:
        show_sql: true
        format_sql: true
        hbm2ddl:
          auto: validate
  mvc:
    format:
      date: iso

eureka:
  instance:
    prefer-ip-address: true
  client:
    register-with-eureka: true
    fetch-registry: true
    service-url:
      defaultZone: http://localhost:8070/eureka
#      defaultZone: http://eureka-server:8070/eureka

server:
  port: 8085


minio:
  bucket: images
#  url: https://minio:9090
  url: http://localhost:9000
  access-key: minioadmin
  secret-key: minioadmin

logging:
  level:
    root: INFO
    org.scuni: INFO

keycloak:
  admin:
    client-id: admin-cli
    client-secret: 9l7KeUeYFWsKBQkPNqLVMRgmBOK1BRx8
  server-url: http://localhost:9082
  realm: scuni
  grant-type: client_credentials