spring:
  application:
    name: user-service


#  datasource:
#    url: jdbc:postgresql://localhost:5432/postgres
#    driver-class-name: org.postgresql.Driver
#    username: postgres
#    password: pass
#    hikari:
#      allow-pool-suspension: true
#  jpa:
#    database-platform: org.hibernate.dialect.PostgreSQLDialect
#  datasource:
#    url: jdbc:postgresql://localhost:5432/postgres
#    driver-class-name: org.postgresql.Driver
#    username: postgres
#    password: pass
#  jpa:
#    properties.hibernate:
#      show_sql: true
#      format_sql: true

#  cloud:
#    loadbalancer:
#      ribbon:
#        enabled: false


server:
  port: 8080


management:
  endpoints:
    web:
      exposure:
        include: '*'

eureka:
  instance:
    preferIpAddress: true
  client:
    registerWithEureka: true
    fetchRegistry: true
    serviceUrl:
      defaultZone: http://eureka-server:8070/eureka/

logging:
  level:
    com.netflix: WARN
    org.springframework.web: WARN
    org.org.scuni: DEBUG